### ISSUE TITLE
For Cud?

### ISSUE THREAD

**Issue by Alexey-T** [seppestas/intel-hex-syntax#1]
Hi. It is strange format, I see it 1st time. Maybe possible to make CudaText (Synwrite) lexer?

**Comment by Alexey-T** [comment]
Okey, i did this

![hex](https://cloud.githubusercontent.com/assets/4154978/17232030/4ddcf6b6-5536-11e6-95c8-41f3cf308f1a.png)

**Comment by seppestas** [comment]
Hello @Alexey-T 

Feel free to take the regexes in this project and put it in your lexer ([I see you already did 🙂](https://sourceforge.net/projects/synwrite-addons/files/Lexers/)).

Note that the `#` character is not actually defined as a comment character. [Syntax tests for ST3](https://www.sublimetext.com/docs/3/syntax.html#testing) just requires there to be a comment character, but Intel Hex does not actually have that concept.

So I think

```
TokenRules = <
    item
      DisplayName = 'Comment'
      StyleName = 'Comment'
      Expression = '^\#.*'
      ColumnFrom = 0
      ColumnTo = 0
    end
```

could/should be removed.
