### ISSUE TITLE
Intel Hex decoding

### ISSUE THREAD

**Issue by krist10an** [seppestas/intel-hex-syntax#3]
Hi,

I noticed you have this nice package for Intel Hex files. I created a similar package that allows you to annotate/decode the file as well a while back, but I never got around to getting it into Package Control. 
If you are interested, feel free to take the code and rewrite or include some of the code into this repository
https://github.com/krist10an/parsehex

**Comment by seppestas** [comment]
Hello @krist10an. My package only provides a syntax definition that changes the colours of the different regions of lines in Intel Hex Files.

It does not do any parsing or annotation like your package does, it is designed to work directly with the files themselves.

I think the only thing that might be useful for you is the `.sublime-syntax` syntax definition for Sublime Text 3, but this would only be useful if your package supports ST3... And even then, AFAIK ST3 also still supports the older .tmLanguage files, so the only "benefits" would be a newer format and testability.
